import type { Metadata, Viewport } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import { PwaRegister } from "@/components/PwaRegister";
import { ThemeSync } from "@/components/ThemeSync";
import { TitleBar } from "@/components/TitleBar";
import { THEME_INIT_SCRIPT } from "@/lib/theme-shared";
import "./globals.css";

// Inter across the whole product (Light → Bold), self-hosted by next/font and
// exposed as --font-inter for the --font-sans token (see globals.css).
const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

// Source Serif 4 for the serif ("Claude-style") answer font, exposed as
// --font-serif for Tailwind's font-serif (see tailwind.config.ts).
const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-serif",
  display: "swap",
});

// Absolute base for resolving OG/icon URLs. Override in production via
// NEXT_PUBLIC_SITE_URL; the fallback keeps local + preview builds happy.
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://assistant.practiscale.co";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "Practiscale Assistant",
  description: "Grounded, sourced answers from your Practiscale knowledge base.",
  icons: {
    icon: [
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  // Installable app (PWA): the manifest is generated by src/app/manifest.ts.
  manifest: "/manifest.webmanifest",
  applicationName: "PractiScale Assistant",
  appleWebApp: { capable: true, title: "Assistant", statusBarStyle: "black-translucent" },
};

export const viewport: Viewport = {
  themeColor: "#161616",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // The init script sets the theme class before hydration, hence
    // suppressHydrationWarning on <html> (its class/style differ by design).
    <html lang="en" className={`${inter.variable} ${sourceSerif.variable}`} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      {/* Theme surfaces come from the shared design tokens (see globals.css).
          min-h-app (100dvh), not min-h-screen (100vh = the LARGE mobile viewport),
          so the page is never taller than the shells and doesn't scroll/jump. */}
      <body className="min-h-app bg-background text-foreground antialiased">
        <TitleBar />
        <ThemeSync />
        <PwaRegister />
        {children}
      </body>
    </html>
  );
}
